DROP TABLE IF EXISTS `sms_providers`;

CREATE TABLE `sms_providers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL default '',
  `type` enum('pager','phone', 'pin') NOT NULL,
  `created_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO sms_providers (name, email, type) VALUES ('3 River Wireless','10digitphonenumber@sms.3rivers.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('ACS Wireless','10digitphonenumber@paging.acswireless.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Alltel','10digitphonenumber@message.alltel.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('AT&T','10digitphonenumber@txt.att.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell Canada','10digitphonenumber@txt.bellmobility.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell Canada','10digitphonenumber@bellmobility.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell Mobility (Canada)','10digitphonenumber@txt.bell.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell Mobility','10digitphonenumber@txt.bellmobility.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Blue Sky Frog','10digitphonenumber@blueskyfrog.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bluegrass Cellular','10digitphonenumber@sms.bluecell.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Boost Mobile','10digitphonenumber@myboostmobile.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('BPL Mobile','10digitphonenumber@bplmobile.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Carolina West Wireless','10digit10digitnumber@cwwsms.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One','10digitphonenumber@mobile.celloneusa.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular South','10digitphonenumber@csouth1.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Centennial Wireless','10digitphonenumber@cwemail.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('CenturyTel','10digitphonenumber@messaging.centurytel.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cingular (Now AT&T)','10digitphonenumber@txt.att.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Clearnet','10digitphonenumber@msg.clearnet.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Comcast','10digitphonenumber@comcastpcs.textmsg.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Corr Wireless Communications','10digitphonenumber@corrwireless.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Dobson','10digitphonenumber@mobile.dobson.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Edge Wireless','10digitphonenumber@sms.edgewireless.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Fido','10digitphonenumber@fido.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Golden Telecom','10digitphonenumber@sms.goldentele.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Helio','10digitphonenumber@messaging.sprintpcs.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Houston Cellular','10digitphonenumber@text.houstoncellular.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Idea Cellular','10digitphonenumber@ideacellular.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Illinois Valley Cellular','10digitphonenumber@ivctext.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Inland Cellular Telephone','10digitphonenumber@inlandlink.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('MCI','10digitphonenumber@pagemci.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Metrocall','10digitpagernumber@page.metrocall.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Metrocall 2-way','10digitpagernumber@my2way.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Metro PCS','10digitphonenumber@mymetropcs.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Microcell','10digitphonenumber@fido.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Midwest Wireless','10digitphonenumber@clearlydigital.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobilcomm','10digitphonenumber@mobilecomm.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('MTS','10digitphonenumber@text.mtsmobility.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Nextel','10digitphonenumber@messaging.nextel.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('OnlineBeep','10digitphonenumber@onlinebeep.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('PCS One','10digitphonenumber@pcsone.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('President\'s Choice','10digitphonenumber@txt.bell.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Public Service Cellular','10digitphonenumber@sms.pscel.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Qwest','10digitphonenumber@qwestmp.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Rogers AT&T Wireless','10digitphonenumber@pcs.rogers.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Rogers Canada','10digitphonenumber@pcs.rogers.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Satellink','10digitpagernumber.pageme@satellink.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Southwestern Bell','10digitphonenumber@email.swbw.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Sprint','10digitphonenumber@messaging.sprintpcs.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Sumcom','10digitphonenumber@tms.suncom.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Surewest Communicaitons','10digitphonenumber@mobile.surewest.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('T-Mobile','10digitphonenumber@tmomail.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Telus','10digitphonenumber@msg.telus.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Tracfone','10digitphonenumber@txt.att.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Triton','10digitphonenumber@tms.suncom.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Unicel','10digitphonenumber@utext.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('US Cellular','10digitphonenumber@email.uscc.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Solo Mobile','10digitphonenumber@txt.bell.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Sprint','10digitphonenumber@messaging.sprintpcs.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Sumcom','10digitphonenumber@tms.suncom.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Surewest Communicaitons','10digitphonenumber@mobile.surewest.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('T-Mobile','10digitphonenumber@tmomail.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Telus','10digitphonenumber@msg.telus.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Triton','10digitphonenumber@tms.suncom.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Unicel','10digitphonenumber@utext.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('US Cellular','10digitphonenumber@email.uscc.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('US West','10digitphonenumber@uswestdatamail.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Verizon','10digitphonenumber@vtext.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Virgin Mobile','10digitphonenumber@vmobl.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Virgin Mobile Canada','10digitphonenumber@vmobile.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('West Central Wireless','10digitphonenumber@sms.wcc.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Western Wireless','10digitphonenumber@cellularonewest.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Chennai RPG Cellular','phonenumber@rpgmail.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Chennai Skycell / Airtel','phonenumber@airtelchennai.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Comviq','number@sms.comviq.se','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Delhi Aritel','phonenumber@airtelmail.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Delhi Hutch','phonenumber@delhi.hutch.co.in','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('DT T-Mobile','phonenumber@t-mobile-sms.de','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Dutchtone / Orange-NL','phonenumber@sms.orange.nl','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('EMT','phonenumber@sms.emt.ee','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Escotel','phonenumber@escotelmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('German T-Mobile','number@t-mobile-sms.de','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Goa BPLMobil','phonenumber@bplmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Golden Telecom','phonenumber@sms.goldentele.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Gujarat Celforce','phonenumber@celforce.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('JSM Tele-Page','pinnumber@jsmtel.com','pin');
INSERT INTO sms_providers (name, email, type) VALUES ('Kerala Escotel','phonenumber@escotelmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Kolkata Airtel','phonenumber@airtelkol.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Kyivstar','number@smsmail.lmt.lv','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Lauttamus Communication','pagernumber@e-page.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('LMT','phonenumber@smsmail.lmt.lv','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Maharashtra BPL Mobile','phonenumber@bplmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Maharashtra Idea Cellular','phonenumber@ideacellular.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Manitoba Telecom Systems','phonenumber@text.mtsmobility.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Meteor','phonenumber@mymeteor.ie','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('MiWorld','phonenumber@m1.com.sg','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobileone','phonenumber@m1.com.sg','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobilfone','phonenumber@page.mobilfone.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobility Bermuda','phonenumber@ml.bm','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobistar Belgium','phonenumber@mobistar.be','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobitel Tanzania','phonenumber@sms.co.tz','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobtel Srbija','phonenumber@mobtel.co.yu','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Movistar','number@correo.movistar.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Mumbai BPL Mobile','phonenumber@bplmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Netcom','phonenumber@sms.netcom.no','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Ntelos','number@pcs.ntelos.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('O2','name@o2.co.uk','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('O2','number@o2imail.co.uk','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('O2 (M-mail)','number@mmail.co.uk','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('One Connect Austria','phonenumber@onemail.at','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('OnlineBeep','10digitphonenumber@onlinebeep.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Optus Mobile','phonenumber@optusmobile.com.au','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Orange','phonenumber@orange.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Orange Mumbai','phonenumber@orangemail.co.in','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Orange NL / Dutchtone','phonenumber@sms.orange.nl','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Oskar','phonenumber@mujoskar.cz','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('P&T Luxembourg','phonenumber@sms.luxgsm.lu','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Personal Communication','sms@pcom.ru (put the number in the subject line)','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Pondicherry BPL Mobile','phonenumber@bplmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Primtel','phonenumber@sms.primtel.ru','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Safaricom','phonenumber@safaricomsms.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Satelindo GSM','phonenumber@satelindogsm.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('SCS-900','phonenumber@scs-900.ru','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('SFR France','phonenumber@sfr.fr','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Simple Freedom','phonenumber@text.simplefreedom.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Smart Telecom','phonenumber@mysmart.mymobile.ph','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Southern LINC','10digitphonenumber@page.southernlinc.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Sunrise Mobile','phonenumber@mysunrise.ch','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Sunrise Mobile','10digitphonenumber@swmsg.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Surewest Communications','phonenumber@freesurf.ch','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Swisscom','phonenumber@bluewin.ch','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('T-Mobile Austria','phonenumber@sms.t-mobile.at','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('T-Mobile Germany','phonenumber@t-d1-sms.de','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('T-Mobile UK','phonenumber@t-mobile.uk.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Tamil Nadu BPL Mobile','phonenumber@bplmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Tele2 Latvia','phonenumber@sms.tele2.lv','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Telefonica Movistar','phonenumber@movistar.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Telenor','phonenumber@mobilpost.no','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Teletouch','10digitpagernumber@pageme.teletouch.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Telia Denmark','phonenumber@gsm1800.telia.dk','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('TIM','10digitphonenumber@timnet.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('TSR Wireless','pagernumber@alphame.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('UMC','phonenumber@sms.umc.com.ua','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Uraltel','phonenumber@sms.uraltel.ru','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Uttar Pradesh Escotel','phonenumber@escotelmobile.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Vessotel','phonenumber@pager.irkutsk.ru','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Vodafone Italy','number@sms.vodafone.it','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Vodafone Japan','phonenumber@c.vodafone.ne.jp','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Vodafone Japan','phonenumber@h.vodafone.ne.jp','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Vodafone Japan','phonenumber@t.vodafone.ne.jp','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Vodafone UK','phonenumber@vodafone.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Wyndtell','number@wyndtell.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Advantage Communications','10digitpagernumber@advantagepaging.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Airtouch Pagers','10digitpagernumber@myairmail.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('AlphaNow','pin@alphanow.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Ameritech Paging','10digitpagernumber@paging.acswireless.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('American Messaging','10digitpagernumber@page.americanmessaging.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Ameritech Clearpath','10digitpagernumber@clearpath.acswireless.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Arch Pagers (PageNet)','10digitpagernumber@archwireless.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('AT&T','10digitphonenumber@mobile.att.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('AT&T Free2Go','10digitphonenumber@mmode.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('AT&T PCS','10digitphonenumber@mobile.att.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('AT&T Pocketnet PCS','10digitphonenumber@dpcs.mobile.att.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Beepwear','10digitphonenumber@beepwear.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell Atlantic','10digitphonenumber@message.bam.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell South','10digitphonenumber@wireless.bellsouth.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell South (Blackberry)','10digitphonenumber@bellsouthtips.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Bell South Mobility','10digitphonenumber@blsdcs.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One (East Coast)','10digitphonenumber@phone.cellone.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One (South West)','10digitphonenumber@swmsg.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One','10digitphonenumber@cellularone.txtmsg.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One','10digitphonenumber@cellularone.textmsg.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One','10digitphonenumber@cell1.textmsg.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One','10digitphonenumber@sbcemail.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Cellular One (West)','10digitphonenumber@mycellone.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Central Vermont Communications','10digitpagernumber@cvcpaging.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Cingular','10digitphonenumber@cingularme.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Communication Specialists','7digitpin@pageme.comspeco.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Cook Paging','10digitpagernumber@cookmail.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Corr Wireless Communications','10digitphonenumber@corrwireless.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Digi-Page / Page Kansas','10digitpagernumber@page.hit.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Galaxy Corporation','10digitpagernumber.epage@sendabeep.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('GCS Paging','10digitpagernumber@webpager.us','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('GrayLink / Porta-Phone','10digitpagernumber@epage.porta-phone.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('GTE','10digitphonenumber@airmessage.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('GTE','10digitphonenumber@gte.pagegate.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('GTE','10digitphonenumber@messagealert.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Infopage Systems','pinnumber@page.infopagesystems.com','pin');
INSERT INTO sms_providers (name, email, type) VALUES ('Indiana Paging Co','10digitphonenumber@inlandlink.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('MCI','10digitphonenumber@pagemci.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Metrocall','10digitphonenumber@page.metrocall.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Mobilecom PA','10digitphonenumber@page.mobilcom.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Morris Wireless','10digitpagernumber@beepone.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Motient','10digitphonenumber@isp.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Nextel','10digitphonenumber@page.nextel.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Omnipoint','10digitphonenumber@omnipointpcs.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Pacific Bell','10digitphonenumber@pacbellpcs.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('PageMart','7digitpinnumber@pagemart.net','pin');
INSERT INTO sms_providers (name, email, type) VALUES ('PageMart Canada','10digitpagernumber@pmcl.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('PageNet Canada','10digitphonenumber@pagegate.pagenet.ca','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('PageOne Northwest','10digitphonenumber@page1nw.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('PCS One','10digitphonenumber@pcsone.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Powertel','10digitphonenumber@voicestream.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Price Communications','10digitphonenumber@mobilecell1se.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('Primeco','10digitphonenumber@email.uscc.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('ProPage','7digitpagernumber@page.propage.net','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Qualcomm','name@pager.qualcomm.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('RAM Page','number@ram-page.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('SBC Ameritech Paging','10digitpagernumber@paging.acswireless.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Skytel Pagers','10digitphonenumber@email.skytel.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('ST Paging','pin@page.stpaging.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Verizon Pagers','10digitpagernumber@myairmail.com','pager');
INSERT INTO sms_providers (name, email, type) VALUES ('Verizon PCS','10digitphonenumber@myvzw.com','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('VoiceStream','10digitphonenumber@voicestream.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('WebLink Wireless','10digitphonenumber@airmessage.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('WebLink Wireless','10digitphonenumber@pagemart.net','phone');
INSERT INTO sms_providers (name, email, type) VALUES ('West Central Wireless','10digitphonenumber@sms.wcc.net','phone');
